import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Axios from "axios";

function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Abyiss Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://abyiss.com">Abyiss!</a>
        </h1>

        <p className={styles.description}>
          Here is current BTC price
        </p>
        <div className={styles.item}>Market: {data.exchange}</div>
        <div className={styles.item}>Price: {data.price}</div>
        <div className={styles.item}>Time: {new Date(parseFloat(data.timestamp)).toISOString()}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Raidel Ruiz
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {

  // Fetch data from external API
  const { data } = await Axios.get(`https://api.abyiss.com/v1/coinbasepro/BTC-USD/currentprice?apiKey=${process.env.TOKEN}`);

  // Pass data to the page via props
  return { props: { data } }
}

export default Home
